name: Build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.branch }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        branch:
          - openwrt-24.10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Building packages
        uses: openwrt/gh-action-sdk@v11
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.branch }}
          FEEDNAME: packages_ci
          PACKAGES: luci-app-wolplus
          NO_REFRESH_CHECK: true
          NO_DEFAULT_FEEDS: true
          EXTRA_FEEDS: src-git|luci|https://github.com/openwrt/luci.git^${{ matrix.branch }}
          V: sc
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-wolplus-${{ matrix.arch }}-${{ matrix.branch }}
          path: bin/packages/${{ matrix.arch }}/packages_ci/*.ipk
      - name: Clean up old workflow runs
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
          delete_workflow_pattern: ${{ github.workflow }}
